catch (int)
{
    // Handle an exception of type int here
    cerr << "We caught an exception of type int" << endl;
}